Repository kowainik/learn4haskell, pull requests merged in 2020-09, with the labels that each got.

#13 Add Learn4Haskell Hacktoberfest Banner
  README.md
  images/HacktoberFest2020-Learn4Haskell-Banner.png
  images/Learn4Haskell.png
Labels: documentation

#16 [#1] PR 1 tasks
  .github/workflows/ci.yml
  learn4haskell.cabal
  src/Chapter1.hs
  src/Learn4haskell.hs
  test/Spec.hs
Labels: task

#17 [#2] PR 2 tasks
  learn4haskell.cabal
  src/Chapter2.hs
Labels: task

#18 [#3] PR 3 tasks
  learn4haskell.cabal
  src/Chapter3.hs
Labels: task

#19 [#4] PR 4 tasks
  learn4haskell.cabal
  src/Chapter4.hs
Labels: task

#20 [#12] Explore 'doctest' testing for testing GHCi tasks
  .github/workflows/ci.yml
  learn4haskell.cabal
  src/Chapter1.hs
  src/Chapter2.hs
  src/Chapter3.hs
  src/Chapter4.hs
  test/DoctestChapter1.hs
  test/DoctestChapter2.hs
  test/DoctestChapter3.hs
  test/DoctestChapter4.hs
Labels: tests

#21 Add tests for Chapter 1
  .github/workflows/ci.yml
  learn4haskell.cabal
  test/Spec.hs
  test/Test/Chapter1.hs
  test/Test/Chapter2.hs
  test/Test/Chapter3.hs
  test/Test/Chapter4.hs
Labels: tests

#22 Fixes to tasks in Chapter 1
  src/Chapter1.hs
Labels: documentation, task

#23 Add tests for Chapter 2
  .github/workflows/ci.yml
  src/Chapter2.hs
  test/Test/Chapter2.hs
Labels: tests

#24 Fixes to Chapter Two
  src/Chapter2.hs
  test/Test/Chapter2.hs
Labels: documentation, task

#25 [#6] Add tests for Chapter 4
  .github/workflows/ci.yml
  src/Chapter3.hs
  src/Chapter4.hs
  test/Test/Chapter4.hs
Labels: tests

#27 [#14] Add PR template
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  README.md
  images/HacktoberFest2020-Learn4Haskell-Banner.png
Labels: enhancement

#28 Fixes to Chapter 4 tests
  test/Test/Chapter4.hs
Labels: enhancement

#29 [#15] Create Makefile with commands
  Makefile
Labels: CI, documentation

#30 Add note in the end about opening a PR
  src/Chapter1.hs
  src/Chapter2.hs
  src/Chapter3.hs
  src/Chapter4.hs
Labels: documentation

#31 [#5] Main project description
  README.md
  src/Chapter1.hs
  src/Chapter2.hs
  src/Chapter3.hs
  src/Chapter4.hs
Labels: documentation
