Repository kowainik/learn4haskell, pull requests merged in 2020-10, with the labels that each got.

#35 grammar
  README.md
Labels: documentation

#44 [#41] Add newlines to fix doctest for the second chapter
  README.md
  src/Chapter2.hs
Labels: bug

#48 Characterize strong and static typing separately
  src/Chapter1.hs
Labels: chapter1, enhancement

#50 Trim Chapter1, Task 9 reference solution
  src/Chapter1.hs
Labels: tests

#55 Improve some wording in Chapter 3 tasks
  src/Chapter3.hs
Labels: chapter3

#46 quickCheck test for two tasks in chapter one
  learn4haskell.cabal
  test/Test/Chapter1.hs
Labels: tests

#62 Update Test of Chapter2.hs
  test/Test/Chapter2.hs
Labels: documentation, tests

#88 docs(Readme): Avoid unknown ghcup command error
  README.md
Labels: documentation

#149 Update Readme with more verbose english
  README.md
Labels: documentation

#141 Tests: Improve tests titles
  Makefile
  test/Test/Chapter1.hs
  test/Test/Chapter2.hs
  test/Test/Chapter4.hs
Labels: hacktoberfest-accepted, tests

#151 Fix a typo where wrong function is called in example
  src/Chapter1.hs
Labels: documentation, tests

#139 add test chapter 1 task 7
  test/Test/Chapter1.hs
Labels: tests

#156 Even more typos
  src/Chapter2.hs
  src/Chapter3.hs
  src/Chapter4.hs
Labels: documentation

#158 Changed 'append number 3' to 'add number 3'
  src/Chapter2.hs
Labels: documentation

#214 Fix typos in chapter 2.
  src/Chapter2.hs
Labels: documentation

#230 fix typo in chapter 3
  src/Chapter3.hs
Labels: documentation

#235 Update Chapter1.hs
  src/Chapter1.hs
Labels: documentation

#242 typos in Chapter1.hs
  test/Test/Chapter1.hs
Labels: documentation, tests

#243 Issue: README.md: *boiling #167
  README.md
Labels: documentation

#248 Fix typo in chapter 3
  src/Chapter3.hs
Labels: chapter3, documentation

#308 Fix typo 'MkNight' -> 'MkKnight'
  src/Chapter3.hs
Labels: documentation

#312 Typo fix
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation
