Repository kowainik/learn4haskell, pull requests merged in 2020-11, with the labels that each got.

#331 [#26] Property tests: rewind & duplicate
  test/Test/Chapter1.hs
  test/Test/Chapter2.hs
Labels: chapter 2, chapter1, tests

#335 Fix typo
  src/Chapter4.hs
Labels: chapter4, documentation

#343 Typos Chapters 1, 2, 3 & 4
  README.md
  src/Chapter1.hs
  src/Chapter2.hs
  src/Chapter3.hs
  src/Chapter4.hs
Labels: documentation

#350 Update haskell action to prevent errors
  .github/workflows/ci.yml
Labels: CI, library :books:

#357 Add dependabot
  .github/dependabot.yml
Labels: CI
